#!/bin/bash

selected=$(echo "󰤄 Sleep
 Restart
 Shutdown
󰍃 Logout" | rofi -dmenu -p "Power Options")

if [[ $selected == "Sleep" ]]; then
  systemctl suspend
elif [[ $selected == "Restart" ]]; then
  reboot
elif [[ $selected == "Shutdown" ]]; then
  poweroff
elif [[ $selected == "Logout" ]]; then
  i3-msg exit
fi
