#!/bin/bash

wallpaper=/home/mate/Pictures/Wallpapers/current-wallpaper

while getopts "m:" flag; do
  case $flag in
    m) num_mon=$OPTARG ;;
  esac
done

feh --bg-scale $wallpaper

if [[ $num_mon ]]; then
  $HOME/.config/polybar/polylaunch.sh -m $num_mon
fi
# $HOME/util/xborder-inactive/launch.sh
