#!/bin/bash

wallpaper=/home/mate/Pictures/Wallpapers/current-wallpaper

feh --bg-scale $wallpaper

# if [[ $num_mon ]]; then
# /home/mate/.config/polybar/polylaunch.sh
# fi
# $HOME/util/xborder-inactive/launch.sh
