#!/bin/bash

launch_polybar=""

while getopts "p" flag; do
  case $flag in
    p) launch_polybar=1 ;;
  esac
done

feh --bg-scale $WALLPAPER

if [[ $launch_polybar ]]; then
  $HOME/.config/polybar/polylaunch.sh &
fi
# $HOME/util/xborder-inactive/launch.sh
