#!/bin/bash

# sleep with builtins only
snore()
{
    local IFS
    [[ -n "${_snore_fd:-}" ]] || exec {_snore_fd}<> <(:)
    read ${1:+-t "$1"} -u $_snore_fd || :
}

self=$$
sc_ids=$(pgrep -f screen-autodetect | xargs)
bash_ids=$(pgrep -f /bin/bash | xargs)
candidates=$(echo $bash_ids | grep -Po "($(echo $sc_ids | sed "s/ /|/g"))" | grep -v $self)
if [[ $candidates ]]; then
  echo $candidates | xargs -L1 kill
fi

SCREENLAYOUT_DIR=$(dirname $(realpath $0))

screens() {
  xrandr | grep -Po "^\S+" | tail -n +2
}

# returns 0 for disconnected and 1 for connected
connected() {
  xrandr | grep "^$1" | grep -Po "\sconnected\s" | wc -l
}

apply_connected_status() {
  dpms_monitor_status=$(xset q | grep Monitor | grep -Po "^\s*\K.+")
  echo "dpms_monitor_status: $dpms_monitor_status"
  if [[ $dpms_monitor_status == "Monitor is Off" ]]; then
    return
  fi

  LAUNCH_POLYBAR=$LAUNCH_POLYBAR $SCREENLAYOUT_DIR/displayMulti 1> /dev/null 2> /dev/null &
  notify-send -t 2000 "$(xrandr --listactivemonitors)"
}

declare -A LAST_CONNECTED_STATUS
for display in $(screens)
do
  LAST_CONNECTED_STATUS[$display]=$(connected $display)
done

apply_connected_status
echo "Applied initially"

while true
do
  CONNECTION_CHANGED=
  for display in $(screens)
  do
    CONNECTED=$(connected $display)

    if [[ $CONNECTED != ${LAST_CONNECTED_STATUS[$display]} ]]; then
      echo "Connection for display $display changed"
      LAST_CONNECTED_STATUS[$display]=$CONNECTED
      CONNECTION_CHANGED=1
    fi
  done
  if [ $CONNECTION_CHANGED ]; then
    LAUNCH_POLYBAR=1 apply_connected_status
    # apply_connected_status
    echo "Applying screen updates..."
  fi
  snore 1
done
