#!/bin/bash

language="python" # hardcoded language of choice for this year
year=$(date +%Y)
day=$(date +%d)
lang_dir="$language/"
year_dir="$lang_dir/_$year"
day_dir="$year_dir/Day$day"

files_to_open=(
    "$day_dir/day*"
    "input/$year/day$day.txt"
    "input/$year/day00.txt"
)

cd ~/projects/advent_calendar/
nvim --listen /tmp/nvim-aoc.pipe +only -o $(IFS=' '; echo ${files_to_open[@]})
