#!/bin/sh
#
# setxkbmap -device $(xinput list | grep "Virtual core XTEST keyboard" | sed -e 's/.\+=\([0-9]\+\).\+/\1/') gb
sleep .5 &&
setxkbmap -layout gb &&
sleep .5 &&
xdotool keyup Shift_L Shift_R Control_L Control_R Alt_L Alt_R Super_L Super_R Hyper_L Hyper_R Caps_Lock 204 205 206 207 &&
notify-send -t 2000 "KB Fixed"
