#!/bin/bash

device_ids=$(xsetwacom --list devices | grep -P "\d+" -o)
primary=$(xrandr | grep -oP ".+?(?= connected primary)")

device_id_to_name() {
  id=$1
  xsetwacom --list devices | grep $id | grep -Po "^.+?\s\s+" | awk '{$1=$1};1'
}

if [ -z "$device_ids" ]; then
  echo "[Wacom] No Wacom devices found"
fi


for id in $device_ids
do
  device=$(device_id_to_name $id)
  echo "device: $device"
  if [ ! -z "$primary" ]; then
    xsetwacom --set "$device" MapToOutput "$primary"
  else
    echo "[Wacom] Could not map to primary output - primary output not found"
  fi

  xsetwacom --set "$device" Rotate half # Rotates by 181 deg - pen sleeve on left
  # xsetwacom --set "$device" Button 3 "key Shift" # write
  xsetwacom --set "$device" Button 3 "key e" # xournal
  # xsetwacom --set "$device" Button 2 "key +space" # write
  xsetwacom --set "$device" Button 2 "key +shift d" # xournal
  xsetwacom -set "$device" PanScrollThreshold 200
done

