#!/bin/bash

# $1 - session name
# ...
# $i - extra args
# ...
# $n - command to run

if [[ -z $1 ]]; then
  return
fi

exists=$(tmux ls 2>&1 | grep -Po "^$1:")
if [[ -z $exists ]]; then
  echo "Creating session:$1"
  tmux new-session -d -s "$@"
else
    echo "Session already exists"
fi
